baseURL = '/'
copyright = "Made by Gabriela Iwama with <a href='https://github.com/timothygebhard/barks'>barks</a>."
languageCode = 'en-us'
title = 'Gabriela'
theme = 'barks'

[params]
    [params.social]
        show_social = true
        email = 'gabrielaiwama@gmail.com'

    [params.colors]
        background_color = "Snow"

[markup.goldmark.renderer]
    unsafe= true


[menu]
    [[menu.main]]
        name = "blog"
        url = "/blog"
        weight = 1
